### PR TITLE
Add user_base_impact and detailed breakage for zoom css

### PR DESCRIPTION
**Pull request by ksy36**
Screen Shot 2022-07-21 at 1 44 57 PM

### CODE REVIEW

**Comment by ksy36** [comment]
I'm in between `medium` and `large`, as it affects a few important sites in Japan and one in Netherlands, but not sure whether they're "very popular".

**Comment by jgraham** [comment]
The spreadsheet here is very nice; I'm starting to think we should bite the bullet and put that information in the kb directly (affected domain, platform, notes on impact, last reproduced date, has intervention, notes). The site rankings we could presumably pull directly from the Tranco API given the domain, and then we could compute the serverity from those inputs.

**Review by jgraham — APPROVED** [review]
I agree that this is somewhere between medium and large, and it makes more sense to err on the side of large.

**Review by denschub — APPROVED** [review]
Amazing investigation. I agree with everything sad, and just like James, I too would err on the side of the larger value. :)

**Comment by ksy36** [comment]
Thanks for the feedback :) Thinking to wait for https://github.com/webcompat/knowledge-base/pull/71 to be merged and then add the data from the spreadsheet to the breakage section.

**Comment by ksy36** [comment]
I've added the detailed breakage, should be ready for review now :)

**Review by jgraham — APPROVED** [review]
Thanks!

**Pull request merged**
