### PR TITLE
Add entry for a problem with some users hitting LocalStorage limit when trying to open Wordle game page

### PR DESCRIPTION
**Pull request by ksy36**
https://bugzilla.mozilla.org/show_bug.cgi?id=1755206

### CODE REVIEW

**Review by jgraham — APPROVED** [review]
I wonder if we should make a more general issue about breakage when reaching the localStorage limit, and use wordle as an example. I also wonder if this happens in Chrome, or what the actual platform difference is.

**Comment by denschub** [comment]
I think I agree with @jgraham! An entry saying "localStorage limited to X" would be a bit like "VideoInput on macOS is limited to 720p", and would make it easier to correlate other breakage if we find them :)

**Comment by ksy36** [comment]
Oh yeah, good point :)

**Review by denschub — APPROVED** [review]

**Comment by ksy36** [comment]
Thanks!

**Pull request merged**
